# Generated by Django 4.2.5 on 2023-10-07 17:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker",
            name="calories",
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="description",
        ),
        migrations.RemoveField(
            model_name="tracker",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="tracker",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=(400, None),
                upload_to="tracker/",
            ),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="image_alt",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
