# Generated by Django 4.2.5 on 2023-10-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0002_remove_tracker_calories_remove_tracker_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="calories",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="image_alt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="tracker",
            name="portion_size",
            field=models.CharField(max_length=200),
        ),
    ]
