# Generated by Django 4.2.5 on 2023-10-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("tracker", "0004_alter_tracker_calories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tracker",
            name="user",
        ),
        migrations.AddField(
            model_name="tracker",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="profiles.profile",
            ),
        ),
    ]
