# Generated by Django 4.2.5 on 2023-10-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("tracker", "0005_remove_tracker_user_tracker_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trackers",
                to="profiles.profile",
            ),
        ),
    ]
