# Generated by Django 4.2.5 on 2023-10-13 20:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0006_alter_tracker_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tracker",
            old_name="profile",
            new_name="user",
        ),
    ]
